image: gitpod/workspace-base

tasks:
- name: install gfastats
  command: |
    cd /workspace
    wget https://github.com/vgl-hub/gfastats/releases/download/v1.3.6/gfastats.v1.3.6-linux.zip
    unzip gfastats.v1.3.6-linux.zip
    chmod a+x ./gfastats
    export PATH=/workspace:$PATH

workspaceLocation: "/workspace"
